# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1

# =================================
# = Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.gmail.com
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_EMAIL}
    properties:
      "[mail.transport.protocol]": smtp
      "[mail.smtp.port]": 587
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: ERROR
    org.flywaydb: ERROR

# =================================
# = Realmeet
# =================================
realmeet:
  allocations:
    maxFilterLimit: 50
  email:
    templates:
      allocationCreated:
        subject: Novo agendamento de sala criado
        templateName: allocation-created.html
      allocationUpdated:
        subject: Novo agendamento de sala alterado
        templateName: allocation-updated.html
      allocationDeleted:
        subject: Novo agendamento de sala cancelado
        templateName: allocation-deleted.html
      allocationReport:
        subject: Relat√≥rio de agendamento de sala
        templateName: allocation-report.html